import { toKenyaDateString } from './kenyaTime.js'

export const AUTO_CLOCK_OUT_HOURS = 12
export const MINIMUM_WORK_HOURS_PER_DAY = 8
const AUTO_CLOCK_OUT_MS = AUTO_CLOCK_OUT_HOURS * 60 * 60 * 1000

export function listWorkDaysInRange(fromDate, toDate) {
  const dates = []
  const cursor = new Date(`${fromDate}T12:00:00`)
  const end = new Date(`${toDate}T12:00:00`)
  while (cursor <= end) {
    const day = cursor.getDay()
    if (day >= 1 && day <= 6) {
      dates.push(cursor.toISOString().slice(0, 10))
    }
    cursor.setDate(cursor.getDate() + 1)
  }
  return dates
}

function kenyaDayBounds(dateStr) {
  const start = new Date(`${dateStr}T00:00:00+03:00`)
  const end = new Date(start.getTime() + 24 * 60 * 60 * 1000)
  return { start, end }
}

function overlapMilliseconds(intervalStart, intervalEnd, dateStr) {
  const { start: dayStart, end: dayEnd } = kenyaDayBounds(dateStr)
  const overlapStart = Math.max(intervalStart.getTime(), dayStart.getTime())
  const overlapEnd = Math.min(intervalEnd.getTime(), dayEnd.getTime())
  return Math.max(0, overlapEnd - overlapStart)
}

function sortEventsChronologically(events) {
  return [...events].sort(
    (a, b) => new Date(a.occurredAt).getTime() - new Date(b.occurredAt).getTime(),
  )
}

export function withAutoClockOutEvents(events, referenceNow = new Date()) {
  const nowMs = referenceNow.getTime()
  const grouped = new Map()

  for (const event of events) {
    if (!grouped.has(event.employeeId)) {
      grouped.set(event.employeeId, [])
    }
    grouped.get(event.employeeId).push(event)
  }

  const synthetic = []
  for (const [employeeId, employeeEvents] of grouped) {
    const sorted = sortEventsChronologically(employeeEvents)
    let openClockIn = null

    for (const event of sorted) {
      if (event.eventType === 'clock_in') {
        openClockIn = event
      }
      if (event.eventType === 'clock_out') {
        openClockIn = null
      }
    }

    if (!openClockIn) {
      continue
    }

    const clockInTime = new Date(openClockIn.occurredAt)
    const autoOutTime = new Date(clockInTime.getTime() + AUTO_CLOCK_OUT_MS)
    if (autoOutTime.getTime() > nowMs) {
      continue
    }

    const sourceEventId = `auto-12h-${openClockIn.id}`
    if (events.some((event) => event.sourceEventId === sourceEventId)) {
      continue
    }

    synthetic.push({
      id: sourceEventId,
      employeeId,
      eventType: 'clock_out',
      occurredAt: autoOutTime.toISOString(),
      deviceId: 'AUTO-12H',
      sourceEventId,
      autoGenerated: true,
    })
  }

  return sortEventsChronologically([...events, ...synthetic])
}

export function employeeClockedInOnDay(events, employeeId, dateStr) {
  return events.some(
    (event) =>
      event.employeeId === employeeId &&
      event.eventType === 'clock_in' &&
      toKenyaDateString(event.occurredAt) === dateStr,
  )
}

export function calculateDayWorkedHours(events, employeeId, dateStr, referenceNow = new Date()) {
  const normalized = withAutoClockOutEvents(events, referenceNow)
  const employeeEvents = normalized.filter((event) => event.employeeId === employeeId)
  let openClockIn = null
  let totalMs = 0

  for (const event of sortEventsChronologically(employeeEvents)) {
    if (event.eventType === 'clock_in') {
      openClockIn = new Date(event.occurredAt)
      continue
    }
    if (event.eventType === 'clock_out' && openClockIn) {
      totalMs += overlapMilliseconds(openClockIn, new Date(event.occurredAt), dateStr)
      openClockIn = null
    }
  }

  return Number((totalMs / (1000 * 60 * 60)).toFixed(2))
}

export function buildAttendanceExceptionReport(
  employees,
  period,
  attendanceEvents,
  referenceNow = new Date(),
) {
  if (!period) {
    return []
  }

  const workDays = listWorkDaysInRange(period.startDate, period.endDate)
  const rows = []

  for (const employee of employees) {
    for (const dateStr of workDays) {
      const clockedIn = employeeClockedInOnDay(attendanceEvents, employee.id, dateStr)
      const hoursWorked = calculateDayWorkedHours(
        attendanceEvents,
        employee.id,
        dateStr,
        referenceNow,
      )

      if (!clockedIn) {
        rows.push({
          employeeId: employee.id,
          name: employee.name,
          department: employee.department ?? '',
          date: dateStr,
          issue: 'no_clock_in',
          hoursWorked: 0,
        })
        continue
      }

      if (hoursWorked < MINIMUM_WORK_HOURS_PER_DAY) {
        rows.push({
          employeeId: employee.id,
          name: employee.name,
          department: employee.department ?? '',
          date: dateStr,
          issue: 'under_hours',
          hoursWorked,
        })
      }
    }
  }

  return rows.sort((a, b) => {
    if (a.date === b.date) {
      return a.name.localeCompare(b.name)
    }
    return a.date.localeCompare(b.date)
  })
}

export function getAttendanceExceptionLabel(issue) {
  if (issue === 'no_clock_in') {
    return 'No clock-in'
  }
  if (issue === 'under_hours') {
    return 'Under 8 hours'
  }
  return issue
}
