import { compareEmployeesByName } from './employeeFields.js'
import { isPayrollParticipant } from './employeePay.js'
import { toKenyaDateString } from './kenyaTime.js'

export const AUTO_CLOCK_OUT_HOURS = 12
export const MINIMUM_WORK_HOURS_PER_DAY = 8
const AUTO_CLOCK_OUT_MS = AUTO_CLOCK_OUT_HOURS * 60 * 60 * 1000

export function listWorkDaysInRange(fromDate, toDate) {
  const dates = []
  const cursor = new Date(`${fromDate}T12:00:00`)
  const end = new Date(`${toDate}T12:00:00`)
  while (cursor <= end) {
    const day = cursor.getDay()
    if (day >= 1 && day <= 6) {
      dates.push(cursor.toISOString().slice(0, 10))
    }
    cursor.setDate(cursor.getDate() + 1)
  }
  return dates
}

function kenyaDayBounds(dateStr) {
  const start = new Date(`${dateStr}T00:00:00+03:00`)
  const end = new Date(start.getTime() + 24 * 60 * 60 * 1000)
  return { start, end }
}

function overlapMilliseconds(intervalStart, intervalEnd, dateStr) {
  const { start: dayStart, end: dayEnd } = kenyaDayBounds(dateStr)
  const overlapStart = Math.max(intervalStart.getTime(), dayStart.getTime())
  const overlapEnd = Math.min(intervalEnd.getTime(), dayEnd.getTime())
  return Math.max(0, overlapEnd - overlapStart)
}

function sortEventsChronologically(events) {
  return [...events].sort(
    (a, b) => new Date(a.occurredAt).getTime() - new Date(b.occurredAt).getTime(),
  )
}

export function withAutoClockOutEvents(events, referenceNow = new Date()) {
  const nowMs = referenceNow.getTime()
  const grouped = new Map()

  for (const event of events) {
    if (!grouped.has(event.employeeId)) {
      grouped.set(event.employeeId, [])
    }
    grouped.get(event.employeeId).push(event)
  }

  const synthetic = []
  for (const [employeeId, employeeEvents] of grouped) {
    const sorted = sortEventsChronologically(employeeEvents)
    let openClockIn = null

    for (const event of sorted) {
      if (event.eventType === 'clock_in') {
        openClockIn = event
      }
      if (event.eventType === 'clock_out') {
        openClockIn = null
      }
    }

    if (!openClockIn) {
      continue
    }

    const clockInTime = new Date(openClockIn.occurredAt)
    const autoOutTime = new Date(clockInTime.getTime() + AUTO_CLOCK_OUT_MS)
    if (autoOutTime.getTime() > nowMs) {
      continue
    }

    const sourceEventId = `auto-12h-${openClockIn.id}`
    if (events.some((event) => event.sourceEventId === sourceEventId)) {
      continue
    }

    synthetic.push({
      id: sourceEventId,
      employeeId,
      eventType: 'clock_out',
      occurredAt: autoOutTime.toISOString(),
      deviceId: 'AUTO-12H',
      sourceEventId,
      autoGenerated: true,
    })
  }

  return sortEventsChronologically([...events, ...synthetic])
}

function isAutoClockOutEvent(event) {
  return (
    event?.deviceId === 'AUTO-12H' ||
    event?.autoGenerated === true ||
    String(event?.id ?? '').startsWith('auto-12h-')
  )
}

export function employeeClockedInOnDay(events, employeeId, dateStr) {
  return events.some(
    (event) =>
      event.employeeId === employeeId &&
      event.eventType === 'clock_in' &&
      toKenyaDateString(event.occurredAt) === dateStr,
  )
}

/** First clock-in and last clock-out on the Kenya calendar day (manual outs preferred). */
export function getEmployeeClockTimesForDay(events, employeeId, dateStr) {
  const dayEvents = sortEventsChronologically(
    (events ?? []).filter(
      (event) =>
        event.employeeId === employeeId && toKenyaDateString(event.occurredAt) === dateStr,
    ),
  )
  const clockIn = dayEvents.find((event) => event.eventType === 'clock_in') ?? null
  const manualOuts = dayEvents.filter(
    (event) => event.eventType === 'clock_out' && !isAutoClockOutEvent(event),
  )
  const clockOut =
    manualOuts.at(-1) ??
    dayEvents.filter((event) => event.eventType === 'clock_out').at(-1) ??
    null

  return {
    clockInAt: clockIn?.occurredAt ?? null,
    clockOutAt: clockOut?.occurredAt ?? null,
    clockOutIsAuto: Boolean(clockOut && isAutoClockOutEvent(clockOut)),
  }
}

function employeeClockedOutOnDay(events, employeeId, dateStr) {
  return events.some(
    (event) =>
      event.employeeId === employeeId &&
      event.eventType === 'clock_out' &&
      toKenyaDateString(event.occurredAt) === dateStr &&
      !isAutoClockOutEvent(event),
  )
}

function employeeHasAnyManualEventOnDay(events, employeeId, dateStr) {
  return (
    employeeClockedInOnDay(events, employeeId, dateStr) ||
    employeeClockedOutOnDay(events, employeeId, dateStr)
  )
}

export function employeeHadAutoClockOutForShiftOnDay(
  events,
  employeeId,
  dateStr,
  referenceNow = new Date(),
) {
  const normalized = withAutoClockOutEvents(events, referenceNow)
  const employeeEvents = sortEventsChronologically(
    normalized.filter((event) => event.employeeId === employeeId),
  )
  let openClockIn = null

  for (const event of employeeEvents) {
    if (event.eventType === 'clock_in') {
      openClockIn = event
      continue
    }
    if (event.eventType === 'clock_out' && openClockIn) {
      const clockInDate = toKenyaDateString(openClockIn.occurredAt)
      if (clockInDate === dateStr && isAutoClockOutEvent(event)) {
        return true
      }
      openClockIn = null
    }
  }

  return false
}

export function calculateDayWorkedHours(events, employeeId, dateStr, referenceNow = new Date()) {
  const normalized = withAutoClockOutEvents(events, referenceNow)
  const employeeEvents = normalized.filter((event) => event.employeeId === employeeId)
  let openClockIn = null
  let totalMs = 0

  for (const event of sortEventsChronologically(employeeEvents)) {
    if (event.eventType === 'clock_in') {
      openClockIn = new Date(event.occurredAt)
      continue
    }
    if (event.eventType === 'clock_out' && openClockIn) {
      totalMs += overlapMilliseconds(openClockIn, new Date(event.occurredAt), dateStr)
      openClockIn = null
    }
  }

  return Number((totalMs / (1000 * 60 * 60)).toFixed(2))
}

export function buildAttendanceExceptionReport(
  employees,
  period,
  attendanceEvents,
  referenceNow = new Date(),
) {
  if (!period) {
    return []
  }

  const workDays = listWorkDaysInRange(period.startDate, period.endDate)
  const rows = []

  for (const employee of employees.filter(isPayrollParticipant).sort(compareEmployeesByName)) {
    for (const dateStr of workDays) {
      if (!employeeHasAnyManualEventOnDay(attendanceEvents, employee.id, dateStr)) {
        continue
      }

      const clockedIn = employeeClockedInOnDay(attendanceEvents, employee.id, dateStr)
      const clockedOut = employeeClockedOutOnDay(attendanceEvents, employee.id, dateStr)

      if (clockedOut && !clockedIn) {
        rows.push({
          employeeId: employee.id,
          name: employee.name,
          department: employee.department ?? '',
          date: dateStr,
          issue: 'clock_out_without_clock_in',
          hoursWorked: 0,
        })
        continue
      }

      if (!clockedIn) {
        continue
      }

      const hoursWorked = calculateDayWorkedHours(
        attendanceEvents,
        employee.id,
        dateStr,
        referenceNow,
      )
      const autoClockOut = employeeHadAutoClockOutForShiftOnDay(
        attendanceEvents,
        employee.id,
        dateStr,
        referenceNow,
      )

      if (autoClockOut) {
        rows.push({
          employeeId: employee.id,
          name: employee.name,
          department: employee.department ?? '',
          date: dateStr,
          issue: 'auto_clock_out',
          hoursWorked,
        })
      }

      if (hoursWorked > 0 && hoursWorked < MINIMUM_WORK_HOURS_PER_DAY) {
        rows.push({
          employeeId: employee.id,
          name: employee.name,
          department: employee.department ?? '',
          date: dateStr,
          issue: 'under_hours',
          hoursWorked,
        })
      }
    }
  }

  return rows.sort((a, b) => {
    if (a.date === b.date) {
      return compareEmployeesByName(a, b)
    }
    return a.date.localeCompare(b.date)
  })
}

export function getAttendanceExceptionLabel(issue) {
  if (issue === 'under_hours') {
    return 'Under 8 hours'
  }
  if (issue === 'auto_clock_out') {
    return 'Forgot to clock out'
  }
  if (issue === 'clock_out_without_clock_in') {
    return 'Clock-out without clock-in'
  }
  return issue
}
